-- Auto generated by mySQL workbench
CREATE TABLE `Car` (
  `vin` int NOT NULL,
  `year` int DEFAULT NULL,
  `make` varchar(45) DEFAULT NULL,
  `model` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`vin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Customer` (
  `customerID` int NOT NULL,
  `fname` varchar(45) DEFAULT NULL,
  `lname` varchar(45) DEFAULT NULL,
  `phone#` int DEFAULT NULL,
  `address` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`customerID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Employee` (
  `employeeID` int NOT NULL,
  `fname` varchar(45) DEFAULT NULL,
  `lname` varchar(45) DEFAULT NULL,
  `phone#` int DEFAULT NULL,
  `address` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`employeeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Mechanic` (
  `employeeID` int NOT NULL,
  `yearsOfExperience` int DEFAULT NULL,
  PRIMARY KEY (`employeeID`),
  CONSTRAINT `Mechanic_ibfk_1` FOREIGN KEY (`employeeID`) REFERENCES `Employee` (`employeeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `needs_part` (
  `vin` int NOT NULL,
  `partID` int NOT NULL,
  PRIMARY KEY (`vin`,`partID`),
  KEY `partID` (`partID`),
  CONSTRAINT `needs_part_ibfk_1` FOREIGN KEY (`vin`) REFERENCES `Car` (`vin`),
  CONSTRAINT `needs_part_ibfk_2` FOREIGN KEY (`partID`) REFERENCES `Part` (`partID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Part` (
  `partID` int NOT NULL,
  `partName` varchar(45) DEFAULT NULL,
  `description` text,
  PRIMARY KEY (`partID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Payment` (
  `paymentID` int NOT NULL,
  `paymentDateTime` datetime DEFAULT NULL,
  `amount` int DEFAULT NULL,
  PRIMARY KEY (`paymentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pays` (
  `paymentID` int NOT NULL,
  `customerID` int NOT NULL,
  PRIMARY KEY (`paymentID`,`customerID`),
  KEY `customerID` (`customerID`),
  CONSTRAINT `pays_ibfk_1` FOREIGN KEY (`paymentID`) REFERENCES `Payment` (`paymentID`),
  CONSTRAINT `pays_ibfk_2` FOREIGN KEY (`customerID`) REFERENCES `Customer` (`customerID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `provides` (
  `vin` int NOT NULL,
  `customerID` int NOT NULL,
  PRIMARY KEY (`vin`,`customerID`),
  KEY `customerID` (`customerID`),
  CONSTRAINT `provides_ibfk_1` FOREIGN KEY (`vin`) REFERENCES `Car` (`vin`),
  CONSTRAINT `provides_ibfk_2` FOREIGN KEY (`customerID`) REFERENCES `Customer` (`customerID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Supplier` (
  `supplierID` int NOT NULL,
  `supplierName` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`supplierID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `supplies` (
  `supplierID` int NOT NULL,
  `partID` int NOT NULL,
  PRIMARY KEY (`supplierID`,`partID`),
  KEY `partID` (`partID`),
  CONSTRAINT `supplies_ibfk_1` FOREIGN KEY (`supplierID`) REFERENCES `Supplier` (`supplierID`),
  CONSTRAINT `supplies_ibfk_2` FOREIGN KEY (`partID`) REFERENCES `Part` (`partID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `works_on` (
  `employeeID` int NOT NULL,
  `vin` int NOT NULL,
  `partID` int NOT NULL,
  `repairDate` datetime DEFAULT NULL,
  PRIMARY KEY (`employeeID`,`vin`,`partID`),
  KEY `vin` (`vin`),
  KEY `partID` (`partID`),
  CONSTRAINT `works_on_ibfk_1` FOREIGN KEY (`employeeID`) REFERENCES `Employee` (`employeeID`),
  CONSTRAINT `works_on_ibfk_2` FOREIGN KEY (`vin`) REFERENCES `Car` (`vin`),
  CONSTRAINT `works_on_ibfk_3` FOREIGN KEY (`partID`) REFERENCES `Part` (`partID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
